---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/afterwo1/public_html/
    - /bin/cp -R *.php *.css *.js *.png *.jpg *.jpeg *.webp *.svg *.ico $DEPLOYPATH
    - /bin/cp -R AFTERSPACE $DEPLOYPATH

    